# Generated by Django 5.0.4 on 2026-03-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
    ]
