# Generated by Django 5.0.4 on 2026-03-24 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_about_is_main"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="about",
            name="title",
        ),
    ]
