# Generated by Django 5.0.4 on 2026-03-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_about_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="about",
            name="is_main",
        ),
        migrations.AddField(
            model_name="about",
            name="title",
            field=models.CharField(default=True, max_length=200),
        ),
    ]
