# Generated by Django 5.0.4 on 2026-03-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_about_is_main_about_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
