# Generated by Django 5.0.4 on 2026-03-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_about_is_main"),
    ]

    operations = [
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_description", models.TextField()),
                ("phone1", models.CharField(max_length=20)),
                ("phone2", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("address_noida", models.TextField()),
                ("address_bangalore", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="UsefulLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.CharField(max_length=200)),
            ],
        ),
    ]
