# Generated by Django 5.0.4 on 2026-03-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_footer_usefullink"),
    ]

    operations = [
        migrations.AddField(
            model_name="footer",
            name="linkedin",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="footer",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="footer/"),
        ),
        migrations.AddField(
            model_name="footer",
            name="map_embed",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="footer",
            name="newsletter_title",
            field=models.CharField(default="Subscribe Newsletter", max_length=200),
        ),
        migrations.AddField(
            model_name="footer",
            name="youtube",
            field=models.URLField(blank=True, null=True),
        ),
    ]
