# Generated by Django 5.0.4 on 2026-03-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_footer_linkedin_footer_logo_footer_map_embed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Get in Touch", max_length=200)),
                ("description", models.TextField()),
                ("address", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("map_embed", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
