# Generated by Django 5.0.4 on 2026-03-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_careerpage_jobapplication_officelocation_whyjoin"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("office_type", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Chairman",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="about/")),
            ],
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("board", "Board of Directors"),
                            ("key", "Key Managerial Personnel"),
                            ("leader", "Leadership Team"),
                        ],
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="team/")),
            ],
        ),
    ]
