# Generated by Django 5.0.4 on 2026-03-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_aboutlocation_aboutpage_chairman_teammember"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("icon", models.CharField(blank=True, max_length=10)),
                (
                    "pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="certifications/"
                    ),
                ),
            ],
        ),
    ]
